apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.userService.name }}

spec:
  replicas: {{ .Values.userService.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Values.userService.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.userService.name }}

    spec:
      containers:
        - name: {{ .Values.userService.name }}

          image: "{{ .Values.userService.image.repository }}:{{ .Values.userService.image.tag }}"

          imagePullPolicy: {{ .Values.userService.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.userService.containerPort }}

          env:
            - name: APP_NAME
              value: "{{ .Values.userService.appName }}"

            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_VERSION

            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ENVIRONMENT

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DATABASE_URL